name: l2ksdk
description: Leads2Keys Flutter
homepage: https://github.com/HBproptech/l2ksdk
version: 1.0.24

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  http: ^0.13.5
  webview_flutter: ^4.0.2
  flutter_secure_storage: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.l2ksdk
    iosBundleIdentifier: com.example.l2ksdk
